# Generated by Django 4.2.7 on 2023-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preferences',
            name='home_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
