# Generated by Django 4.2.7 on 2023-12-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0004_alter_user_preferences_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_preferences',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='user_preferences',
            name='interests',
            field=models.CharField(blank=True, choices=[('shopping', 'Shopping'), ('restaurants', 'Restaurants'), ('supermarkets', 'Supermarkets'), ('trails', 'Trails'), ('public_transit', 'Public Transit'), ('theatre', 'Theatre'), ('night_life', 'Night Life'), ('marijuana_dispensary', 'Marijuana Dispensary'), ('cafes', 'Cafes'), ('sports', 'Sports')], default=''),
        ),
        migrations.AlterField(
            model_name='user_preferences',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('0', 'studio'), ('1', 'one bedroom'), ('2', 'two bedrooms'), ('3', 'three bedrooms'), ('4', 'four bedrooms'), ('5', 'five bedrooms'), ('6', 'six bedrooms')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='user_preferences',
            name='heating',
            field=models.CharField(blank=True, choices=[('forced_air', 'Forced Air'), ('radiant_heat', 'Radiant Heat'), ('baseboard', 'Baseboard'), ('central', 'Central Heating'), ('electric', 'Electric'), ('gas', 'Gas'), ('heat_pump', 'Heat Pump'), ('solar', 'Solar'), ('wood_stove', 'Wood Stove')], default=''),
        ),
    ]
